name: autotrend-broadcast
on:
  schedule: [{cron: "*/15 * * * *"}]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  tick:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate signals
        run: |
          TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          cat > signals.json <<JSON
          {"updated":"$TS","items":[
            {"t":"Scanning markets…","s":"AT"},
            {"t":"No.1 momentum: DEMO-PAIR","s":"AT"},
            {"t":"Watchlist refreshed","s":"AT"}
          ]}
          JSON
      - name: Commit
        run: |
          git config user.name "autotrend-bot"
          git config user.email "actions@users.noreply.github.com"
          git add signals.json
          git commit -m "autotrend: refresh signals @ $TS" || exit 0
          git push
